"""Add source_keys and audio_bitrate

Revision ID: 5cbcaa7d2ff8
Revises: e67516c4e660
Create Date: 2026-01-18 16:20:38.203652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cbcaa7d2ff8'
down_revision: Union[str, Sequence[str], None] = 'e67516c4e660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('audio_bitrate', sa.Integer(), nullable=True))
    op.add_column('file_metadata', sa.Column('source_keys', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 'source_keys')
    op.drop_column('file_metadata', 'audio_bitrate')
    # ### end Alembic commands ###
