"""Simplify Export table

Revision ID: 94e4667315c5
Revises: 02a5617de358
Create Date: 2026-01-18 17:05:37.531961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e4667315c5'
down_revision: Union[str, Sequence[str], None] = '02a5617de358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exports', 'bitrate')
    op.drop_column('exports', 'framerate')
    op.drop_column('exports', 'audio_channels')
    op.drop_column('exports', 'codec')
    op.drop_column('exports', 'duration')
    op.drop_column('exports', 'audio_bitrate')
    op.drop_column('exports', 'audio_codec')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exports', sa.Column('audio_codec', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('exports', sa.Column('audio_bitrate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exports', sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('exports', sa.Column('codec', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('exports', sa.Column('audio_channels', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exports', sa.Column('framerate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('exports', sa.Column('bitrate', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
