"""Add audio metadata columns

Revision ID: e67516c4e660
Revises: 9e0cf371198c
Create Date: 2026-01-18 15:47:24.598478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67516c4e660'
down_revision: Union[str, Sequence[str], None] = '9e0cf371198c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('audio_codec', sa.String(), nullable=True))
    op.add_column('file_metadata', sa.Column('audio_channels', sa.Integer(), nullable=True))
    op.add_column('file_metadata', sa.Column('audio_sample_rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 'audio_sample_rate')
    op.drop_column('file_metadata', 'audio_channels')
    op.drop_column('file_metadata', 'audio_codec')
    # ### end Alembic commands ###
